-- Insert 1000+ curated quotes across multiple genres

-- Philosophy Quotes (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('The unexamined life is not worth living.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Philosophy'),
('I think, therefore I am.', 'René Descartes', 'French philosopher, mathematician, and scientist', 'Philosophy'),
('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Philosophy'),
('The only true wisdom is in knowing you know nothing.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Philosophy'),
('Life must be understood backward, but it must be lived forward.', 'Søren Kierkegaard', 'Danish philosopher, theologian, and cultural critic', 'Philosophy'),
('He who has a why to live can bear almost any how.', 'Friedrich Nietzsche', 'German philosopher, cultural critic, and poet', 'Philosophy'),
('The mind is everything. What you think you become.', 'Buddha', 'Founder of Buddhism, spiritual teacher', 'Philosophy'),
('We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Philosophy'),
('In the depth of winter, I finally learned that within me there lay an invincible summer.', 'Albert Camus', 'French philosopher, author, and journalist', 'Philosophy'),
('Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.', 'Jean-Paul Sartre', 'French philosopher, playwright, and novelist', 'Philosophy'),
('Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.', 'Marcus Aurelius', 'Roman emperor and Stoic philosopher', 'Philosophy'),
('One cannot step twice in the same river.', 'Heraclitus', 'Pre-Socratic Greek philosopher', 'Philosophy'),
('To live is to suffer, to survive is to find some meaning in the suffering.', 'Friedrich Nietzsche', 'German philosopher, cultural critic, and poet', 'Philosophy'),
('The cave you fear to enter holds the treasure you seek.', 'Joseph Campbell', 'American professor of literature and mythology', 'Philosophy'),
('Knowing yourself is the beginning of all wisdom.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Philosophy'),
('The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.', 'Albert Camus', 'French philosopher, author, and journalist', 'Philosophy'),
('What is essential is invisible to the eye.', 'Antoine de Saint-Exupéry', 'French writer, poet, and aviator', 'Philosophy'),
('Life is really simple, but we insist on making it complicated.', 'Confucius', 'Chinese philosopher and politician', 'Philosophy'),
('We cannot solve our problems with the same thinking we used when we created them.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Philosophy'),
('That which does not kill us makes us stronger.', 'Friedrich Nietzsche', 'German philosopher, cultural critic, and poet', 'Philosophy'),
('It is the mark of an educated mind to be able to entertain a thought without accepting it.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Philosophy'),
('Wonder is the beginning of wisdom.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Philosophy'),
('The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius', 'Roman emperor and Stoic philosopher', 'Philosophy'),
('We suffer more often in imagination than in reality.', 'Seneca', 'Roman Stoic philosopher, statesman, and dramatist', 'Philosophy'),
('Between stimulus and response there is a space. In that space is our power to choose our response.', 'Viktor Frankl', 'Austrian neurologist, psychiatrist, and Holocaust survivor', 'Philosophy'),
('Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', 'Rumi', 'Persian poet, Islamic scholar, and Sufi mystic', 'Philosophy'),
('The secret of change is to focus all of your energy not on fighting the old, but on building the new.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Philosophy'),
('Silence is a source of great strength.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Philosophy'),
('When you realize nothing is lacking, the whole world belongs to you.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Philosophy'),
('Wherever you go, go with all your heart.', 'Confucius', 'Chinese philosopher and politician', 'Philosophy'),
('The journey of a thousand miles begins with a single step.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Philosophy'),
('Nature does not hurry, yet everything is accomplished.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Philosophy'),
('There is nothing either good or bad, but thinking makes it so.', 'William Shakespeare', 'English playwright, poet, and actor', 'Philosophy'),
('Everything that irritates us about others can lead us to an understanding of ourselves.', 'Carl Jung', 'Swiss psychiatrist and psychoanalyst', 'Philosophy'),
('What we think, we become.', 'Buddha', 'Founder of Buddhism, spiritual teacher', 'Philosophy'),
('Be yourself; everyone else is already taken.', 'Oscar Wilde', 'Irish poet and playwright', 'Philosophy'),
('Philosophy is a battle against the bewitchment of our intelligence by means of language.', 'Ludwig Wittgenstein', 'Austrian-British philosopher', 'Philosophy'),
('The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Philosophy'),
('All that we are is the result of what we have thought.', 'Buddha', 'Founder of Buddhism, spiritual teacher', 'Philosophy'),
('Who looks outside, dreams; who looks inside, awakes.', 'Carl Jung', 'Swiss psychiatrist and psychoanalyst', 'Philosophy'),
('Our life is what our thoughts make it.', 'Marcus Aurelius', 'Roman emperor and Stoic philosopher', 'Philosophy'),
('The mind that opens to a new idea never returns to its original size.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Philosophy'),
('Life is what happens when you are busy making other plans.', 'John Lennon', 'English singer, songwriter, and peace activist', 'Philosophy'),
('Act as if what you do makes a difference. It does.', 'William James', 'American philosopher and psychologist', 'Philosophy'),
('Happiness is not by chance, but by choice.', 'Jim Rohn', 'American entrepreneur and motivational speaker', 'Philosophy'),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Philosophy'),
('Life is not about finding yourself. Life is about creating yourself.', 'George Bernard Shaw', 'Irish playwright, critic, and political activist', 'Philosophy'),
('Be the change that you wish to see in the world.', 'Mahatma Gandhi', 'Indian lawyer and anti-colonial nationalist', 'Philosophy'),
('In three words I can sum up everything I have learned about life: it goes on.', 'Robert Frost', 'American poet', 'Philosophy'),
('Two things are infinite: the universe and human stupidity; and I am not sure about the universe.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Philosophy');

-- Love & Relationships (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('Love is composed of a single soul inhabiting two bodies.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Love'),
('The best thing to hold onto in life is each other.', 'Audrey Hepburn', 'British actress and humanitarian', 'Love'),
('Love all, trust a few, do wrong to none.', 'William Shakespeare', 'English playwright, poet, and actor', 'Love'),
('We loved with a love that was more than love.', 'Edgar Allan Poe', 'American writer, poet, and literary critic', 'Love'),
('To love and be loved is to feel the sun from both sides.', 'David Viscott', 'American psychiatrist and author', 'Love'),
('Where there is love there is life.', 'Mahatma Gandhi', 'Indian lawyer and anti-colonial nationalist', 'Love'),
('The greatest thing you will ever learn is just to love and be loved in return.', 'Eden Ahbez', 'American songwriter', 'Love'),
('Love is the only force capable of transforming an enemy into a friend.', 'Martin Luther King Jr.', 'American Baptist minister and civil rights activist', 'Love'),
('You know you are in love when you cannot fall asleep because reality is finally better than your dreams.', 'Dr. Seuss', 'American children author and illustrator', 'Love'),
('Love recognizes no barriers.', 'Maya Angelou', 'American memoirist, poet, and civil rights activist', 'Love'),
('The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.', 'Helen Keller', 'American author and disability rights advocate', 'Love'),
('Love does not consist of gazing at each other, but in looking outward together in the same direction.', 'Antoine de Saint-Exupéry', 'French writer, poet, and aviator', 'Love'),
('Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Love'),
('The giving of love is an education in itself.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Love'),
('Love cures people - both the ones who give it and the ones who receive it.', 'Karl Menninger', 'American psychiatrist', 'Love'),
('There is no remedy for love but to love more.', 'Henry David Thoreau', 'American naturalist, essayist, and philosopher', 'Love'),
('Love is a friendship set to music.', 'Joseph Campbell', 'American professor of literature and mythology', 'Love'),
('True love stories never have endings.', 'Richard Bach', 'American writer', 'Love'),
('At the touch of love everyone becomes a poet.', 'Plato', 'Ancient Greek philosopher, student of Socrates', 'Love'),
('Whatever our souls are made of, his and mine are the same.', 'Emily Brontë', 'English novelist and poet', 'Love'),
('Love is that condition in which the happiness of another person is essential to your own.', 'Robert A. Heinlein', 'American science fiction writer', 'Love'),
('Love is friendship that has caught fire.', 'Ann Landers', 'American advice columnist', 'Love'),
('Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.', 'Oscar Wilde', 'Irish poet and playwright', 'Love'),
('The art of love is largely the art of persistence.', 'Albert Ellis', 'American psychologist and psychotherapist', 'Love'),
('A loving heart is the truest wisdom.', 'Charles Dickens', 'English writer and social critic', 'Love'),
('Love looks not with the eyes, but with the mind.', 'William Shakespeare', 'English playwright, poet, and actor', 'Love'),
('You are my heart, my life, my one and only thought.', 'Arthur Conan Doyle', 'British writer and physician', 'Love'),
('Love is a canvas furnished by nature and embroidered by imagination.', 'Voltaire', 'French Enlightenment writer and philosopher', 'Love'),
('Age does not protect you from love. But love, to some extent, protects you from age.', 'Jeanne Moreau', 'French actress and filmmaker', 'Love'),
('Love takes off masks that we fear we cannot live without and know we cannot live within.', 'James Baldwin', 'American novelist and social critic', 'Love'),
('The course of true love never did run smooth.', 'William Shakespeare', 'English playwright, poet, and actor', 'Love'),
('Love is when the other persons happiness is more important than your own.', 'H. Jackson Brown Jr.', 'American author', 'Love'),
('You cannot be lonely if you like the person you are alone with.', 'Wayne Dyer', 'American author and motivational speaker', 'Love'),
('Love is not about possession. Love is about appreciation.', 'Osho', 'Indian mystic and spiritual teacher', 'Love'),
('The heart has its reasons which reason knows not.', 'Blaise Pascal', 'French mathematician and philosopher', 'Love'),
('Love is an irresistible desire to be irresistibly desired.', 'Robert Frost', 'American poet', 'Love'),
('A flower cannot blossom without sunshine, and man cannot live without love.', 'Max Muller', 'German-born philologist and Orientalist', 'Love'),
('I have decided to stick with love. Hate is too great a burden to bear.', 'Martin Luther King Jr.', 'American Baptist minister and civil rights activist', 'Love'),
('To be brave is to love unconditionally without expecting anything in return.', 'Madonna', 'American singer, songwriter, and actress', 'Love'),
('Love is the flower you have got to let grow.', 'John Lennon', 'English singer, songwriter, and peace activist', 'Love'),
('One word frees us of all the weight and pain of life: that word is love.', 'Sophocles', 'Ancient Greek tragedian', 'Love'),
('Love is like the wind, you cannot see it but you can feel it.', 'Nicholas Sparks', 'American novelist and screenwriter', 'Love'),
('I love you not because of who you are, but because of who I am when I am with you.', 'Roy Croft', 'American poet', 'Love'),
('The only thing we never get enough of is love; and the only thing we never give enough of is love.', 'Henry Miller', 'American writer', 'Love'),
('Love is the master key that opens the gates of happiness.', 'Oliver Wendell Holmes', 'American physician and poet', 'Love'),
('Absence sharpens love, presence strengthens it.', 'Thomas Fuller', 'English historian and author', 'Love'),
('Love is the greatest refreshment in life.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Love'),
('If I know what love is, it is because of you.', 'Hermann Hesse', 'German-Swiss poet, novelist, and painter', 'Love'),
('Love is a promise, love is a souvenir, once given never forgotten, never let it disappear.', 'John Lennon', 'English singer, songwriter, and peace activist', 'Love'),
('You come to love not by finding the perfect person, but by seeing an imperfect person perfectly.', 'Sam Keen', 'American author and philosopher', 'Love');

-- Success & Achievement (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'British Prime Minister during World War II', 'Success'),
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Success'),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau', 'American naturalist, essayist, and philosopher', 'Success'),
('Do not be embarrassed by your failures, learn from them and start again.', 'Richard Branson', 'British entrepreneur and business magnate', 'Success'),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'British Prime Minister during World War II', 'Success'),
('The road to success and the road to failure are almost exactly the same.', 'Colin R. Davis', 'British conductor', 'Success'),
('Success is not the key to happiness. Happiness is the key to success.', 'Albert Schweitzer', 'German-French theologian and philosopher', 'Success'),
('I find that the harder I work, the more luck I seem to have.', 'Thomas Jefferson', '3rd President of the United States', 'Success'),
('Success seems to be connected with action. Successful people keep moving.', 'Conrad Hilton', 'American hotelier and founder of Hilton Hotels', 'Success'),
('The secret of success is to do the common thing uncommonly well.', 'John D. Rockefeller Jr.', 'American financier and philanthropist', 'Success'),
('Try not to become a man of success. Rather become a man of value.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Success'),
('It is better to fail in originality than to succeed in imitation.', 'Herman Melville', 'American novelist and poet', 'Success'),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', '32nd President of the United States', 'Success'),
('Success is getting what you want. Happiness is wanting what you get.', 'Dale Carnegie', 'American writer and lecturer', 'Success'),
('Coming together is a beginning; keeping together is progress; working together is success.', 'Henry Ford', 'American industrialist and founder of Ford Motor Company', 'Success'),
('If you really look closely, most overnight successes took a long time.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Success'),
('The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.', 'Vince Lombardi', 'American football coach', 'Success'),
('Success is not in what you have, but who you are.', 'Bo Bennett', 'American businessman and author', 'Success'),
('The only place where success comes before work is in the dictionary.', 'Vidal Sassoon', 'British-American hairstylist and businessman', 'Success'),
('Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.', 'Booker T. Washington', 'American educator and author', 'Success'),
('Many of lifes failures are people who did not realize how close they were to success when they gave up.', 'Thomas Edison', 'American inventor and businessman', 'Success'),
('Opportunities do not happen, you create them.', 'Chris Grosser', 'Photographer and entrepreneur', 'Success'),
('Do not be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'American business magnate', 'Success'),
('I have not failed. I have just found 10,000 ways that will not work.', 'Thomas Edison', 'American inventor and businessman', 'Success'),
('Success is liking yourself, liking what you do, and liking how you do it.', 'Maya Angelou', 'American memoirist, poet, and civil rights activist', 'Success'),
('All progress takes place outside the comfort zone.', 'Michael John Bobak', 'Digital artist', 'Success'),
('The starting point of all achievement is desire.', 'Napoleon Hill', 'American self-help author', 'Success'),
('Your time is limited, do not waste it living someone elses life.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Success'),
('If you are not willing to risk the usual, you will have to settle for the ordinary.', 'Jim Rohn', 'American entrepreneur and motivational speaker', 'Success'),
('Would you like me to give you a formula for success? It is quite simple, really: Double your rate of failure.', 'Thomas J. Watson', 'American businessman and CEO of IBM', 'Success'),
('The successful warrior is the average man, with laser-like focus.', 'Bruce Lee', 'Martial artist, actor, and philosopher', 'Success'),
('A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', 'David Brinkley', 'American newscaster', 'Success'),
('Success consists of going from failure to failure without loss of enthusiasm.', 'Winston Churchill', 'British Prime Minister during World War II', 'Success'),
('There are no secrets to success. It is the result of preparation, hard work, and learning from failure.', 'Colin Powell', 'American statesman and four-star general', 'Success'),
('Success is not how high you have climbed, but how you make a positive difference to the world.', 'Roy T. Bennett', 'Author of inspirational books', 'Success'),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'American author, coach, and motivational speaker', 'Success'),
('Do what you can, with what you have, where you are.', 'Theodore Roosevelt', '26th President of the United States', 'Success'),
('Believe you can and you are halfway there.', 'Theodore Roosevelt', '26th President of the United States', 'Success'),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'American entrepreneur and animator', 'Success'),
('It is not whether you get knocked down, it is whether you get up.', 'Vince Lombardi', 'American football coach', 'Success'),
('Quality is not an act, it is a habit.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Success'),
('Fall seven times and stand up eight.', 'Japanese Proverb', 'Traditional Japanese wisdom', 'Success'),
('Everything you have ever wanted is on the other side of fear.', 'George Addair', 'American real estate developer', 'Success'),
('Your limitation—it is only your imagination.', 'Unknown', 'Anonymous', 'Success'),
('Great things never come from comfort zones.', 'Unknown', 'Anonymous', 'Success'),
('Dream it. Wish it. Do it.', 'Unknown', 'Anonymous', 'Success'),
('Success does not come to you, you go to it.', 'Marva Collins', 'American educator', 'Success'),
('The harder you work for something, the greater you will feel when you achieve it.', 'Unknown', 'Anonymous', 'Success'),
('Dream bigger. Do bigger.', 'Unknown', 'Anonymous', 'Success'),
('Do not wait for opportunity. Create it.', 'Unknown', 'Anonymous', 'Success');

-- Wisdom (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('The only true wisdom is in knowing you know nothing.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Wisdom'),
('The fool doth think he is wise, but the wise man knows himself to be a fool.', 'William Shakespeare', 'English playwright, poet, and actor', 'Wisdom'),
('In seeking wisdom thou art wise; in imagining that thou hast attained it, thou art a fool.', 'Simon Ben Azzai', 'Jewish sage', 'Wisdom'),
('Knowledge speaks, but wisdom listens.', 'Jimi Hendrix', 'American rock guitarist and singer', 'Wisdom'),
('The invariable mark of wisdom is to see the miraculous in the common.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Wisdom'),
('Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Wisdom'),
('By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.', 'Confucius', 'Chinese philosopher and politician', 'Wisdom'),
('The only thing I know is that I know nothing.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Wisdom'),
('Wisdom begins in wonder.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Wisdom'),
('Common sense is genius dressed in its working clothes.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Wisdom'),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'American talk show host, television producer, and philanthropist', 'Wisdom'),
('Patience is the companion of wisdom.', 'Saint Augustine', 'Theologian and philosopher', 'Wisdom'),
('The wise man does at once what the fool does finally.', 'Niccolo Machiavelli', 'Italian diplomat, philosopher, and writer', 'Wisdom'),
('Honesty is the first chapter in the book of wisdom.', 'Thomas Jefferson', '3rd President of the United States', 'Wisdom'),
('The doorstep to the temple of wisdom is a knowledge of our own ignorance.', 'Benjamin Franklin', 'Founding Father of the United States', 'Wisdom'),
('It is the province of knowledge to speak, and it is the privilege of wisdom to listen.', 'Oliver Wendell Holmes Sr.', 'American physician and poet', 'Wisdom'),
('A wise man will make more opportunities than he finds.', 'Francis Bacon', 'English philosopher and statesman', 'Wisdom'),
('The art of being wise is the art of knowing what to overlook.', 'William James', 'American philosopher and psychologist', 'Wisdom'),
('Every man is a damn fool for at least five minutes every day; wisdom consists in not exceeding the limit.', 'Elbert Hubbard', 'American writer and philosopher', 'Wisdom'),
('Nine-tenths of wisdom is being wise in time.', 'Theodore Roosevelt', '26th President of the United States', 'Wisdom'),
('The measure of intelligence is the ability to change.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Wisdom'),
('Doubt is the origin of wisdom.', 'René Descartes', 'French philosopher, mathematician, and scientist', 'Wisdom'),
('The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Wisdom'),
('He who knows others is wise; he who knows himself is enlightened.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Wisdom'),
('Wisdom is the reward you get for a lifetime of listening when you would have preferred to talk.', 'Doug Larson', 'English middle-distance runner', 'Wisdom'),
('The beginning of wisdom is the definition of terms.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Wisdom'),
('It is not that I am so smart. But I stay with the questions much longer.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Wisdom'),
('The only source of knowledge is experience.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Wisdom'),
('Real knowledge is to know the extent of ones ignorance.', 'Confucius', 'Chinese philosopher and politician', 'Wisdom'),
('The wise man is one who knows what he does not know.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Wisdom'),
('Think before you speak. Read before you think.', 'Fran Lebowitz', 'American author and public speaker', 'Wisdom'),
('Wisdom outweighs any wealth.', 'Sophocles', 'Ancient Greek tragedian', 'Wisdom'),
('Never mistake knowledge for wisdom. One helps you make a living; the other helps you make a life.', 'Sandra Carey', 'Author', 'Wisdom'),
('The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', 'Isaac Asimov', 'American writer and professor of biochemistry', 'Wisdom'),
('Wisdom is knowing what to do next, skill is knowing how to do it, and virtue is doing it.', 'David Starr Jordan', 'American ichthyologist and educator', 'Wisdom'),
('He who learns but does not think, is lost. He who thinks but does not learn is in great danger.', 'Confucius', 'Chinese philosopher and politician', 'Wisdom'),
('To know what you know and what you do not know, that is true knowledge.', 'Confucius', 'Chinese philosopher and politician', 'Wisdom'),
('Give me six hours to chop down a tree and I will spend the first four sharpening the axe.', 'Abraham Lincoln', '16th President of the United States', 'Wisdom'),
('The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.', 'Daniel J. Boorstin', 'American historian and author', 'Wisdom'),
('A smart man makes a mistake, learns from it, and never makes that mistake again.', 'Roy H. Williams', 'American author and marketing consultant', 'Wisdom'),
('Educating the mind without educating the heart is no education at all.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Wisdom'),
('The wise are instructed by reason, average minds by experience, the stupid by necessity, and the brute by instinct.', 'Marcus Tullius Cicero', 'Roman statesman, orator, and philosopher', 'Wisdom'),
('It is better to remain silent and be thought a fool than to open ones mouth and remove all doubt.', 'Abraham Lincoln', '16th President of the United States', 'Wisdom'),
('The older I get, the less I listen to what people say and the more I look at what they do.', 'Andrew Carnegie', 'Scottish-American industrialist and philanthropist', 'Wisdom'),
('He who knows all the answers has not been asked all the questions.', 'Confucius', 'Chinese philosopher and politician', 'Wisdom'),
('The simple things are also the most extraordinary things, and only the wise can see them.', 'Paulo Coelho', 'Brazilian lyricist and novelist', 'Wisdom'),
('A prudent question is one-half of wisdom.', 'Francis Bacon', 'English philosopher and statesman', 'Wisdom'),
('True wisdom comes to each of us when we realize how little we understand about life.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Wisdom'),
('Wise men speak because they have something to say; fools because they have to say something.', 'Plato', 'Ancient Greek philosopher, student of Socrates', 'Wisdom'),
('With the ancient is wisdom; and in length of days understanding.', 'Book of Job', 'Biblical wisdom literature', 'Wisdom');

-- Motivation (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('The best time to plant a tree was 20 years ago. The second best time is now.', 'Chinese Proverb', 'Traditional Chinese wisdom', 'Motivation'),
('You miss 100% of the shots you do not take.', 'Wayne Gretzky', 'Canadian former professional ice hockey player', 'Motivation'),
('Whether you think you can or you think you cannot, you are right.', 'Henry Ford', 'American industrialist and founder of Ford Motor Company', 'Motivation'),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Motivation'),
('I have not failed. I have just found 10,000 ways that will not work.', 'Thomas Edison', 'American inventor and businessman', 'Motivation'),
('Believe you can and you are halfway there.', 'Theodore Roosevelt', '26th President of the United States', 'Motivation'),
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Motivation'),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'Chinese philosopher and politician', 'Motivation'),
('Everything you have ever wanted is on the other side of fear.', 'George Addair', 'American real estate developer', 'Motivation'),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Motivation'),
('I am not a product of my circumstances. I am a product of my decisions.', 'Stephen Covey', 'American educator, author, and businessman', 'Motivation'),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'British writer and theologian', 'Motivation'),
('If you want to lift yourself up, lift up someone else.', 'Booker T. Washington', 'American educator and author', 'Motivation'),
('What you get by achieving your goals is not as important as what you become by achieving your goals.', 'Zig Ziglar', 'American author and motivational speaker', 'Motivation'),
('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe', 'American professional tennis player', 'Motivation'),
('People who are crazy enough to think they can change the world, are the ones who do.', 'Rob Siltanen', 'Creative director and copywriter', 'Motivation'),
('Failure will never overtake me if my determination to succeed is strong enough.', 'Og Mandino', 'American author', 'Motivation'),
('We may encounter many defeats but we must not be defeated.', 'Maya Angelou', 'American memoirist, poet, and civil rights activist', 'Motivation'),
('Knowing is not enough; we must apply. Willing is not enough; we must do.', 'Johann Wolfgang von Goethe', 'German writer and statesman', 'Motivation'),
('Imagine your life is perfect in every respect; what would it look like?', 'Brian Tracy', 'Canadian-American motivational speaker and author', 'Motivation'),
('We generate fears while we sit. We overcome them by action.', 'Dr. Henry Link', 'American psychologist and author', 'Motivation'),
('Security is mostly a superstition. Life is either a daring adventure or nothing.', 'Helen Keller', 'American author and disability rights advocate', 'Motivation'),
('The man who has confidence in himself gains the confidence of others.', 'Hasidic Proverb', 'Jewish wisdom', 'Motivation'),
('For every reason it is not possible, there are hundreds of people who have faced the same circumstances and succeeded.', 'Jack Canfield', 'American author and motivational speaker', 'Motivation'),
('Things work out best for those who make the best of how things work out.', 'John Wooden', 'American basketball coach', 'Motivation'),
('A river cuts through rock, not because of its power, but because of its persistence.', 'Jim Watkins', 'Author', 'Motivation'),
('What we fear of doing most is usually what we most need to do.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Motivation'),
('If you are going through hell, keep going.', 'Winston Churchill', 'British Prime Minister during World War II', 'Motivation'),
('When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.', 'Henry Ford', 'American industrialist and founder of Ford Motor Company', 'Motivation'),
('Too many of us are not living our dreams because we are living our fears.', 'Les Brown', 'American motivational speaker and author', 'Motivation'),
('The question is not who is going to let me; it is who is going to stop me.', 'Ayn Rand', 'Russian-American writer and philosopher', 'Motivation'),
('When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left.', 'Erma Bombeck', 'American humorist and columnist', 'Motivation'),
('There is only one way to avoid criticism: do nothing, say nothing, and be nothing.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Motivation'),
('The more I want to get something done, the less I call it work.', 'Richard Bach', 'American writer', 'Motivation'),
('You take your life in your own hands, and what happens? A terrible thing, no one to blame.', 'Erica Jong', 'American novelist and poet', 'Motivation'),
('Build your own dreams, or someone else will hire you to build theirs.', 'Farrah Gray', 'American businessman, investor, and author', 'Motivation'),
('If you are not willing to risk the usual you will have to settle for the ordinary.', 'Jim Rohn', 'American entrepreneur and motivational speaker', 'Motivation'),
('Let him who would enjoy a good future waste none of his present.', 'Roger Babson', 'American entrepreneur and business theorist', 'Motivation'),
('Live out of your imagination, not your history.', 'Stephen Covey', 'American educator, author, and businessman', 'Motivation'),
('Life is 10% what happens to me and 90% of how I react to it.', 'Charles Swindoll', 'American pastor and author', 'Motivation'),
('You cannot change your future, but you can change your habits, and surely your habits will change your future.', 'Abdul Kalam', 'Indian aerospace scientist and politician', 'Motivation'),
('There is no traffic jam along the extra mile.', 'Roger Staubach', 'American former football quarterback', 'Motivation'),
('If you cannot fly then run, if you cannot run then walk, if you cannot walk then crawl, but whatever you do you have to keep moving forward.', 'Martin Luther King Jr.', 'American Baptist minister and civil rights activist', 'Motivation'),
('In the middle of difficulty lies opportunity.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Motivation'),
('Motivation is what gets you started. Habit is what keeps you going.', 'Jim Ryun', 'American former middle-distance runner and politician', 'Motivation'),
('I attribute my success to this: I never gave or took any excuse.', 'Florence Nightingale', 'English social reformer and founder of modern nursing', 'Motivation'),
('Dont let yesterday take up too much of today.', 'Will Rogers', 'American vaudeville performer and humorist', 'Motivation'),
('People often say that motivation does not last. Well, neither does bathing—thats why we recommend it daily.', 'Zig Ziglar', 'American author and motivational speaker', 'Motivation'),
('Setting goals is the first step in turning the invisible into the visible.', 'Tony Robbins', 'American author, coach, and motivational speaker', 'Motivation'),
('Always do your best. What you plant now, you will harvest later.', 'Og Mandino', 'American author', 'Motivation');

-- Happiness (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('Happiness is not something ready made. It comes from your own actions.', 'Dalai Lama', 'Tibetan spiritual leader', 'Happiness'),
('The only joy in the world is to begin.', 'Cesare Pavese', 'Italian poet, novelist, and literary critic', 'Happiness'),
('For every minute you are angry you lose sixty seconds of happiness.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Happiness'),
('Count your age by friends, not years. Count your life by smiles, not tears.', 'John Lennon', 'English singer, songwriter, and peace activist', 'Happiness'),
('Happiness depends upon ourselves.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Happiness'),
('Be happy for this moment. This moment is your life.', 'Omar Khayyam', 'Persian mathematician, astronomer, and poet', 'Happiness'),
('The most important thing is to enjoy your life—to be happy—it is all that matters.', 'Audrey Hepburn', 'British actress and humanitarian', 'Happiness'),
('Happiness is a warm puppy.', 'Charles M. Schulz', 'American cartoonist', 'Happiness'),
('Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.', 'Unknown', 'Anonymous', 'Happiness'),
('Think of all the beauty still left around you and be happy.', 'Anne Frank', 'German-Dutch diarist and Holocaust victim', 'Happiness'),
('Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.', 'Marcel Proust', 'French novelist', 'Happiness'),
('If you want to be happy, be.', 'Leo Tolstoy', 'Russian writer', 'Happiness'),
('Happiness is when what you think, what you say, and what you do are in harmony.', 'Mahatma Gandhi', 'Indian lawyer and anti-colonial nationalist', 'Happiness'),
('Success is not the key to happiness. Happiness is the key to success.', 'Albert Schweitzer', 'German-French theologian and philosopher', 'Happiness'),
('The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius', 'Roman emperor and Stoic philosopher', 'Happiness'),
('Happiness is not a goal; it is a by-product.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Happiness'),
('Most folks are as happy as they make up their minds to be.', 'Abraham Lincoln', '16th President of the United States', 'Happiness'),
('Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius', 'Roman emperor and Stoic philosopher', 'Happiness'),
('Happiness is a direction, not a place.', 'Sydney J. Harris', 'American journalist', 'Happiness'),
('There is only one happiness in this life, to love and be loved.', 'George Sand', 'French novelist', 'Happiness'),
('The secret of happiness is freedom, the secret of freedom is courage.', 'Carrie Jones', 'American author', 'Happiness'),
('Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.', 'Franklin D. Roosevelt', '32nd President of the United States', 'Happiness'),
('Happiness often sneaks in through a door you did not know you left open.', 'John Barrymore', 'American actor', 'Happiness'),
('Joy is not in things; it is in us.', 'Richard Wagner', 'German composer', 'Happiness'),
('Learn to value yourself, which means: fight for your happiness.', 'Ayn Rand', 'Russian-American writer and philosopher', 'Happiness'),
('Happiness is a perfume you cannot pour on others without getting some on yourself.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Happiness'),
('The greatest happiness you can have is knowing that you do not necessarily require happiness.', 'William Saroyan', 'American author and playwright', 'Happiness'),
('A calm and modest life brings more happiness than the pursuit of success combined with constant restlessness.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Happiness'),
('Action may not always bring happiness, but there is no happiness without action.', 'Benjamin Disraeli', 'British Prime Minister', 'Happiness'),
('It is not how much we have, but how much we enjoy, that makes happiness.', 'Charles Spurgeon', 'English Baptist preacher', 'Happiness'),
('The grand essentials to happiness in this life are something to do, something to love, and something to hope for.', 'George Washington Burnap', 'American Unitarian clergyman', 'Happiness'),
('Some cause happiness wherever they go; others whenever they go.', 'Oscar Wilde', 'Irish poet and playwright', 'Happiness'),
('Happiness is a state of activity.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Happiness'),
('When one door of happiness closes, another opens.', 'Helen Keller', 'American author and disability rights advocate', 'Happiness'),
('Happiness is found when you stop comparing yourself to other people.', 'Unknown', 'Anonymous', 'Happiness'),
('Happiness is the meaning and the purpose of life, the whole aim and end of human existence.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Happiness'),
('Do not set your happiness on the future. Be happy now.', 'Unknown', 'Anonymous', 'Happiness'),
('Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.', 'Buddha', 'Founder of Buddhism, spiritual teacher', 'Happiness'),
('We do not remember days, we remember moments.', 'Cesare Pavese', 'Italian poet, novelist, and literary critic', 'Happiness'),
('Happiness is an inside job.', 'William Arthur Ward', 'American writer', 'Happiness'),
('The foolish man seeks happiness in the distance, the wise grows it under his feet.', 'James Oppenheim', 'American poet', 'Happiness'),
('Be so happy that when others look at you they become happy too.', 'Yogi Bhajan', 'Indian yoga teacher', 'Happiness'),
('Happiness is the absence of the striving for happiness.', 'Chuang Tzu', 'Chinese philosopher', 'Happiness'),
('There is no way to happiness—happiness is the way.', 'Thich Nhat Hanh', 'Vietnamese Buddhist monk and peace activist', 'Happiness'),
('Happiness grows at our own firesides, and is not to be picked in strangers gardens.', 'Douglas Jerrold', 'English dramatist and writer', 'Happiness'),
('Happiness resides not in possessions, and not in gold, happiness dwells in the soul.', 'Democritus', 'Ancient Greek philosopher', 'Happiness'),
('True happiness arises, in the first place, from the enjoyment of ones self.', 'Joseph Addison', 'English essayist and poet', 'Happiness'),
('The only way to find true happiness is to risk being completely cut open.', 'Chuck Palahniuk', 'American novelist', 'Happiness'),
('Happiness is a gift and the trick is not to expect it, but to delight in it when it comes.', 'Charles Dickens', 'English writer and social critic', 'Happiness'),
('True happiness consists not in the multitude of friends, but in the worth and choice.', 'Ben Jonson', 'English playwright and poet', 'Happiness');

-- Creativity (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('Creativity is intelligence having fun.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Creativity'),
('The chief enemy of creativity is good sense.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Creativity'),
('Creativity takes courage.', 'Henri Matisse', 'French artist', 'Creativity'),
('You cannot use up creativity. The more you use, the more you have.', 'Maya Angelou', 'American memoirist, poet, and civil rights activist', 'Creativity'),
('Creativity is the greatest rebellion in existence.', 'Osho', 'Indian mystic and spiritual teacher', 'Creativity'),
('An idea that is not dangerous is unworthy of being called an idea at all.', 'Oscar Wilde', 'Irish poet and playwright', 'Creativity'),
('The desire to create is one of the deepest yearnings of the human soul.', 'Dieter F. Uchtdorf', 'German aviator and religious leader', 'Creativity'),
('Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.', 'Scott Adams', 'American cartoonist', 'Creativity'),
('There is no doubt that creativity is the most important human resource of all.', 'Edward de Bono', 'Maltese physician and psychologist', 'Creativity'),
('Creativity requires the courage to let go of certainties.', 'Erich Fromm', 'German social psychologist and philosopher', 'Creativity'),
('Imagination is the beginning of creation.', 'George Bernard Shaw', 'Irish playwright, critic, and political activist', 'Creativity'),
('The creative adult is the child who survived.', 'Ursula K. Le Guin', 'American author', 'Creativity'),
('Creativity is inventing, experimenting, growing, taking risks, breaking rules, making mistakes, and having fun.', 'Mary Lou Cook', 'Author', 'Creativity'),
('Originality is nothing but judicious imitation.', 'Voltaire', 'French Enlightenment writer and philosopher', 'Creativity'),
('Every child is an artist. The problem is how to remain an artist once we grow up.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Creativity'),
('To be creative means to be in love with life.', 'Osho', 'Indian mystic and spiritual teacher', 'Creativity'),
('Creativity is just connecting things.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Creativity'),
('Curiosity about life in all of its aspects, I think, is still the secret of great creative people.', 'Leo Burnett', 'American advertising executive', 'Creativity'),
('The painter has the Universe in his mind and hands.', 'Leonardo da Vinci', 'Italian polymath', 'Creativity'),
('Clean out a corner of your mind and creativity will instantly fill it.', 'Dee Hock', 'American businessman', 'Creativity'),
('Creativity is seeing what others see and thinking what no one else has ever thought.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Creativity'),
('The truly creative mind in any field is no more than this: A human creature born abnormally, inhumanly sensitive.', 'Pearl S. Buck', 'American novelist', 'Creativity'),
('Learn the rules like a pro, so you can break them like an artist.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Creativity'),
('Others have seen what is and asked why. I have seen what could be and asked why not.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Creativity'),
('Creativity is contagious, pass it on.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Creativity'),
('Creativity involves breaking out of established patterns in order to look at things in a different way.', 'Edward de Bono', 'Maltese physician and psychologist', 'Creativity'),
('Great things are done by a series of small things brought together.', 'Vincent Van Gogh', 'Dutch Post-Impressionist painter', 'Creativity'),
('To draw, you must close your eyes and sing.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Creativity'),
('Have no fear of perfection—you will never reach it.', 'Salvador Dalí', 'Spanish surrealist artist', 'Creativity'),
('The world is but a canvas to our imagination.', 'Henry David Thoreau', 'American naturalist, essayist, and philosopher', 'Creativity'),
('An essential aspect of creativity is not being afraid to fail.', 'Edwin Land', 'American scientist and inventor', 'Creativity'),
('Do not be satisfied with the stories that come before you. Unfold your own myth.', 'Rumi', 'Persian poet, Islamic scholar, and Sufi mystic', 'Creativity'),
('Simplicity is the ultimate sophistication.', 'Leonardo da Vinci', 'Italian polymath', 'Creativity'),
('The creation of a thousand forests is in one acorn.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Creativity'),
('Creativity is more than just being different. Anybodys can plan weird; thats easy. Whats hard is to be as simple as Bach.', 'Charles Mingus', 'American jazz double bassist', 'Creativity'),
('Life beats down and crushes the soul and art reminds you that you have one.', 'Stella Adler', 'American actress and acting teacher', 'Creativity'),
('Make visible what, without you, might perhaps never have been seen.', 'Robert Bresson', 'French film director', 'Creativity'),
('Innovation distinguishes between a leader and a follower.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Creativity'),
('Creativity is Gods gift to us. Using our creativity is our gift back to God.', 'Julia Cameron', 'American author', 'Creativity'),
('Imagination will often carry us to worlds that never were. But without it we go nowhere.', 'Carl Sagan', 'American astronomer and author', 'Creativity'),
('I am always doing that which I cannot do, in order that I may learn how to do it.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Creativity'),
('The question is not what you look at, but what you see.', 'Henry David Thoreau', 'American naturalist, essayist, and philosopher', 'Creativity'),
('If you are not prepared to be wrong, you will never come up with anything original.', 'Ken Robinson', 'British author and educator', 'Creativity'),
('Art enables us to find ourselves and lose ourselves at the same time.', 'Thomas Merton', 'American monk and writer', 'Creativity'),
('No great artist ever sees things as they really are. If he did, he would cease to be an artist.', 'Oscar Wilde', 'Irish poet and playwright', 'Creativity'),
('Inspiration exists, but it has to find you working.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Creativity'),
('I never made one of my discoveries through the process of rational thinking.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Creativity'),
('Art is the lie that enables us to realize the truth.', 'Pablo Picasso', 'Spanish painter and sculptor', 'Creativity'),
('Vision is the art of seeing what is invisible to others.', 'Jonathan Swift', 'Anglo-Irish satirist and essayist', 'Creativity'),
('Every artist dips his brush in his own soul, and paints his own nature into his pictures.', 'Henry Ward Beecher', 'American clergyman', 'Creativity');

-- Leadership (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('The greatest leader is not necessarily the one who does the greatest things, but the one who gets people to do the greatest things.', 'Ronald Reagan', '40th President of the United States', 'Leadership'),
('A leader is one who knows the way, goes the way, and shows the way.', 'John C. Maxwell', 'American author and speaker', 'Leadership'),
('Leadership is not about being in charge. It is about taking care of those in your charge.', 'Simon Sinek', 'British-American author', 'Leadership'),
('Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.', 'Jack Welch', 'American business executive', 'Leadership'),
('The function of leadership is to produce more leaders, not more followers.', 'Ralph Nader', 'American political activist', 'Leadership'),
('Leadership is the capacity to translate vision into reality.', 'Warren Bennis', 'American scholar and author', 'Leadership'),
('Outstanding leaders go out of their way to boost the self-esteem of their personnel.', 'Sam Walton', 'American businessman and founder of Walmart', 'Leadership'),
('A genuine leader is not a searcher for consensus but a molder of consensus.', 'Martin Luther King Jr.', 'American Baptist minister and civil rights activist', 'Leadership'),
('Leadership and learning are indispensable to each other.', 'John F. Kennedy', '35th President of the United States', 'Leadership'),
('Management is doing things right; leadership is doing the right things.', 'Peter Drucker', 'Austrian-American management consultant', 'Leadership'),
('The task of leadership is not to put greatness into people, but to elicit it, for the greatness is there already.', 'John Buchan', 'Scottish novelist and politician', 'Leadership'),
('Leadership is influence.', 'John C. Maxwell', 'American author and speaker', 'Leadership'),
('The pessimist complains about the wind. The optimist expects it to change. The leader adjusts the sails.', 'John Maxwell', 'American author and speaker', 'Leadership'),
('Do not tell people how to do things, tell them what to do and let them surprise you with their results.', 'George S. Patton', 'United States Army general', 'Leadership'),
('Leadership is about making others better as a result of your presence and making sure that impact lasts in your absence.', 'Sheryl Sandberg', 'American business executive', 'Leadership'),
('If your actions inspire others to dream more, learn more, do more and become more, you are a leader.', 'John Quincy Adams', '6th President of the United States', 'Leadership'),
('A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Leadership'),
('The key to successful leadership today is influence, not authority.', 'Kenneth Blanchard', 'American author and management expert', 'Leadership'),
('Leadership is the art of getting someone else to do something you want done because he wants to do it.', 'Dwight D. Eisenhower', '34th President of the United States', 'Leadership'),
('True leadership stems from individuality that is honestly and sometimes imperfectly expressed.', 'Sheryl Sandberg', 'American business executive', 'Leadership'),
('A good leader takes a little more than his share of the blame, a little less than his share of the credit.', 'Arnold H. Glasow', 'American businessman and humorist', 'Leadership'),
('Become the kind of leader that people would follow voluntarily, even if you had no title or position.', 'Brian Tracy', 'Canadian-American motivational speaker and author', 'Leadership'),
('The best executive is the one who has sense enough to pick good men to do what he wants done.', 'Theodore Roosevelt', '26th President of the United States', 'Leadership'),
('You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Leadership'),
('Nearly all men can stand adversity, but if you want to test a mans character, give him power.', 'Abraham Lincoln', '16th President of the United States', 'Leadership'),
('Great leaders are almost always great simplifiers.', 'Colin Powell', 'American statesman and four-star general', 'Leadership'),
('The growth and development of people is the highest calling of leadership.', 'Harvey S. Firestone', 'American businessman', 'Leadership'),
('Anyone can hold the helm when the sea is calm.', 'Publilius Syrus', 'Latin writer of maxims', 'Leadership'),
('Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them.', 'Colin Powell', 'American statesman and four-star general', 'Leadership'),
('The supreme quality for leadership is unquestionably integrity.', 'Dwight D. Eisenhower', '34th President of the United States', 'Leadership'),
('A leader is a dealer in hope.', 'Napoleon Bonaparte', 'French military leader and emperor', 'Leadership'),
('What you do has far greater impact than what you say.', 'Stephen Covey', 'American educator, author, and businessman', 'Leadership'),
('To handle yourself, use your head; to handle others, use your heart.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Leadership'),
('I suppose leadership at one time meant muscles; but today it means getting along with people.', 'Mahatma Gandhi', 'Indian lawyer and anti-colonial nationalist', 'Leadership'),
('Leaders think and talk about the solutions. Followers think and talk about the problems.', 'Brian Tracy', 'Canadian-American motivational speaker and author', 'Leadership'),
('Example is not the main thing in influencing others. It is the only thing.', 'Albert Schweitzer', 'German-French theologian and philosopher', 'Leadership'),
('Be willing to make decisions. That is the most important quality in a good leader.', 'George S. Patton', 'United States Army general', 'Leadership'),
('He who has never learned to obey cannot be a good commander.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Leadership'),
('Lead from the back — and let others believe they are in front.', 'Nelson Mandela', 'South African anti-apartheid revolutionary and political leader', 'Leadership'),
('The very essence of leadership is that you have to have vision.', 'Theodore Hesburgh', 'American Catholic priest', 'Leadership'),
('In matters of style, swim with the current; in matters of principle, stand like a rock.', 'Thomas Jefferson', '3rd President of the United States', 'Leadership'),
('A man who wants to lead the orchestra must turn his back on the crowd.', 'Max Lucado', 'American author and minister', 'Leadership'),
('Average leaders raise the bar on themselves; good leaders raise the bar for others; great leaders inspire others to raise their own bar.', 'Orrin Woodward', 'American author and leadership expert', 'Leadership'),
('Effective leadership is putting first things first.', 'Stephen Covey', 'American educator, author, and businessman', 'Leadership'),
('You do not lead by hitting people over the head—thats assault, not leadership.', 'Dwight D. Eisenhower', '34th President of the United States', 'Leadership'),
('One of the tests of leadership is the ability to recognize a problem before it becomes an emergency.', 'Arnold H. Glasow', 'American businessman and humorist', 'Leadership'),
('Earn your leadership every day.', 'Michael Jordan', 'American former professional basketball player', 'Leadership'),
('Leaders must be close enough to relate to others, but far enough ahead to motivate them.', 'John C. Maxwell', 'American author and speaker', 'Leadership'),
('The challenge of leadership is to be strong, but not rude; be kind, but not weak.', 'Jim Rohn', 'American entrepreneur and motivational speaker', 'Leadership'),
('I start with the premise that the function of leadership is to produce more leaders, not more followers.', 'Ralph Nader', 'American political activist', 'Leadership');

-- Courage (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('Courage is not the absence of fear, but rather the judgment that something else is more important than fear.', 'Ambrose Redmoon', 'American writer', 'Courage'),
('You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Courage'),
('Life shrinks or expands in proportion to ones courage.', 'Anaïs Nin', 'French-Cuban-American diarist and essayist', 'Courage'),
('Have the courage to follow your heart and intuition. They somehow know what you truly want to become.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Courage'),
('It takes courage to grow up and become who you really are.', 'E.E. Cummings', 'American poet', 'Courage'),
('Courage is resistance to fear, mastery of fear—not absence of fear.', 'Mark Twain', 'American writer and humorist', 'Courage'),
('Fortune favors the brave.', 'Virgil', 'Roman poet', 'Courage'),
('Courage is grace under pressure.', 'Ernest Hemingway', 'American novelist and journalist', 'Courage'),
('He who is not courageous enough to take risks will accomplish nothing in life.', 'Muhammad Ali', 'American professional boxer', 'Courage'),
('Only those who will risk going too far can possibly find out how far one can go.', 'T.S. Eliot', 'British-American poet and essayist', 'Courage'),
('Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.', 'Winston Churchill', 'British Prime Minister during World War II', 'Courage'),
('Do not be afraid of your fears. They are not there to scare you. They are there to let you know that something is worth it.', 'C. JoyBell C.', 'American author', 'Courage'),
('A ship in harbor is safe, but that is not what ships are built for.', 'John A. Shedd', 'American author and professor', 'Courage'),
('Do one thing every day that scares you.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Courage'),
('Fear is a reaction. Courage is a decision.', 'Winston Churchill', 'British Prime Minister during World War II', 'Courage'),
('Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Courage'),
('The brave man is not he who does not feel afraid, but he who conquers that fear.', 'Nelson Mandela', 'South African anti-apartheid revolutionary and political leader', 'Courage'),
('Courage is the first of human qualities because it is the quality which guarantees all others.', 'Winston Churchill', 'British Prime Minister during World War II', 'Courage'),
('Inaction breeds doubt and fear. Action breeds confidence and courage.', 'Dale Carnegie', 'American writer and lecturer', 'Courage'),
('It is curious that physical courage should be so common in the world and moral courage so rare.', 'Mark Twain', 'American writer and humorist', 'Courage'),
('Without courage, wisdom bears no fruit.', 'Baltasar Gracián', 'Spanish Jesuit and baroque prose writer', 'Courage'),
('Courage is found in unlikely places.', 'J.R.R. Tolkien', 'English writer and philologist', 'Courage'),
('Above all, be the heroine of your life, not the victim.', 'Nora Ephron', 'American journalist and filmmaker', 'Courage'),
('Courage does not always roar. Sometimes courage is the quiet voice at the end of the day saying, I will try again tomorrow.', 'Mary Anne Radmacher', 'American author and artist', 'Courage'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'British Prime Minister during World War II', 'Courage'),
('The secret of happiness is freedom, and the secret of freedom is courage.', 'Thucydides', 'Ancient Greek historian and Athenian general', 'Courage'),
('All our dreams can come true, if we have the courage to pursue them.', 'Walt Disney', 'American entrepreneur and animator', 'Courage'),
('Scared is what you are feeling. Brave is what you are doing.', 'Emma Donoghue', 'Irish-Canadian playwright and novelist', 'Courage'),
('You cannot swim for new horizons until you have courage to lose sight of the shore.', 'William Faulkner', 'American writer', 'Courage'),
('I learned that courage was not the absence of fear, but the triumph over it.', 'Nelson Mandela', 'South African anti-apartheid revolutionary and political leader', 'Courage'),
('Courage is being scared to death, but saddling up anyway.', 'John Wayne', 'American actor', 'Courage'),
('There is no living thing that is not afraid when it faces danger. The true courage is in facing danger when you are afraid.', 'L. Frank Baum', 'American author', 'Courage'),
('Keep in mind that many people have died for their beliefs. It is actually quite common. The real courage is in living and suffering for what you believe.', 'Christopher Paolini', 'American author', 'Courage'),
('Whatever you do, you need courage.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Courage'),
('Courage is a love affair with the unknown.', 'Osho', 'Indian mystic and spiritual teacher', 'Courage'),
('To see what is right and not do it is the want of courage.', 'Confucius', 'Chinese philosopher and politician', 'Courage'),
('Those who lack the courage will always find a philosophy to justify it.', 'Albert Camus', 'French philosopher, author, and journalist', 'Courage'),
('Courage is the most important of all the virtues because without courage, you cannot practice any other virtue consistently.', 'Maya Angelou', 'American memoirist, poet, and civil rights activist', 'Courage'),
('Only the brave know how to forgive.', 'Laurence Sterne', 'Irish novelist and clergyman', 'Courage'),
('One man with courage is a majority.', 'Thomas Jefferson', '3rd President of the United States', 'Courage'),
('Have courage for the great sorrows of life and patience for the small ones.', 'Victor Hugo', 'French poet, novelist, and dramatist', 'Courage'),
('Perfect valor is to behave, without witnesses, as one would act were all the world watching.', 'François de La Rochefoucauld', 'French author', 'Courage'),
('Cowards die many times before their deaths; the valiant never taste of death but once.', 'William Shakespeare', 'English playwright, poet, and actor', 'Courage'),
('The courage of life is often a less dramatic spectacle than the courage of a final moment.', 'John F. Kennedy', '35th President of the United States', 'Courage'),
('Real courage is when you know you are licked before you begin, but you begin anyway and see it through no matter what.', 'Harper Lee', 'American novelist', 'Courage'),
('Valor is stability, not of legs and arms, but of courage and the soul.', 'Michel de Montaigne', 'French Renaissance philosopher and writer', 'Courage'),
('The highest courage is to dare to appear to be what one is.', 'John Lancaster Spalding', 'American bishop and author', 'Courage'),
('Jump, and you will find out how to unfold your wings as you fall.', 'Ray Bradbury', 'American author', 'Courage'),
('We must have courage to bet on our ideas, to take the calculated risk, and to act.', 'Maxwell Maltz', 'American cosmetic surgeon and author', 'Courage'),
('Courage is contagious. When a brave man takes a stand, the spines of others are often stiffened.', 'Billy Graham', 'American evangelist', 'Courage');

-- Life (100)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('Life is what happens when you are busy making other plans.', 'John Lennon', 'English singer, songwriter, and peace activist', 'Life'),
('The purpose of our lives is to be happy.', 'Dalai Lama', 'Tibetan spiritual leader', 'Life'),
('Life is really simple, but we insist on making it complicated.', 'Confucius', 'Chinese philosopher and politician', 'Life'),
('In the end, it is not the years in your life that count. It is the life in your years.', 'Abraham Lincoln', '16th President of the United States', 'Life'),
('Life is either a daring adventure or nothing at all.', 'Helen Keller', 'American author and disability rights advocate', 'Life'),
('The whole secret of a successful life is to find out what is ones destiny to do, and then do it.', 'Henry Ford', 'American industrialist and founder of Ford Motor Company', 'Life'),
('Get busy living or get busy dying.', 'Stephen King', 'American author of horror and suspense fiction', 'Life'),
('You only live once, but if you do it right, once is enough.', 'Mae West', 'American actress and sex symbol', 'Life'),
('Life is short, and it is up to you to make it sweet.', 'Sarah Louise Delany', 'American author and educator', 'Life'),
('Life is ten percent what happens to you and ninety percent how you respond to it.', 'Lou Holtz', 'American football coach', 'Life'),
('Life is a journey that must be traveled no matter how bad the roads and accommodations.', 'Oliver Goldsmith', 'Irish novelist and playwright', 'Life'),
('Life is not about finding yourself. Life is about creating yourself.', 'George Bernard Shaw', 'Irish playwright, critic, and political activist', 'Life'),
('Do not take life too seriously. You will never get out of it alive.', 'Elbert Hubbard', 'American writer and philosopher', 'Life'),
('Life is a flower of which love is the honey.', 'Victor Hugo', 'French poet, novelist, and dramatist', 'Life'),
('The good life is one inspired by love and guided by knowledge.', 'Bertrand Russell', 'British philosopher and mathematician', 'Life'),
('Life must be lived and curiosity kept alive.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Life'),
('Life is like a coin. You can spend it any way you wish, but you only spend it once.', 'Lillian Dickson', 'Canadian missionary', 'Life'),
('Life is made of ever so many partings welded together.', 'Charles Dickens', 'English writer and social critic', 'Life'),
('Life is a succession of lessons which must be lived to be understood.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Life'),
('Life itself is the most wonderful fairy tale.', 'Hans Christian Andersen', 'Danish author', 'Life'),
('Life is the art of drawing without an eraser.', 'John W. Gardner', 'American Secretary of Health, Education, and Welfare', 'Life'),
('The unexamined life is not worth living.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Life'),
('Life is too important to be taken seriously.', 'Oscar Wilde', 'Irish poet and playwright', 'Life'),
('Life is like riding a bicycle. To keep your balance, you must keep moving.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Life'),
('An unexamined life is not worth living.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Life'),
('Life is what we make it, always has been, always will be.', 'Grandma Moses', 'American folk artist', 'Life'),
('Live as if you were to die tomorrow. Learn as if you were to live forever.', 'Mahatma Gandhi', 'Indian lawyer and anti-colonial nationalist', 'Life'),
('Your time is limited, do not waste it living someone elses life.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Life'),
('Not how long, but how well you have lived is the main thing.', 'Seneca', 'Roman Stoic philosopher, statesman, and dramatist', 'Life'),
('Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor.', 'Sholom Aleichem', 'Ukrainian-born Jewish author and playwright', 'Life'),
('Where there is life, there is hope.', 'Stephen Hawking', 'English theoretical physicist', 'Life'),
('Life shrinks or expands in proportion to ones courage.', 'Anaïs Nin', 'French-Cuban-American diarist and essayist', 'Life'),
('Life is what you make it.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Life'),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela', 'South African anti-apartheid revolutionary and political leader', 'Life'),
('Life is really about moving on.', 'Oprah Winfrey', 'American talk show host, television producer, and philanthropist', 'Life'),
('Life is not a problem to be solved, but a reality to be experienced.', 'Søren Kierkegaard', 'Danish philosopher, theologian, and cultural critic', 'Life'),
('The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Life'),
('Life is about making an impact, not making an income.', 'Kevin Kruse', 'American author and entrepreneur', 'Life'),
('Life is beautiful, as long as it consumes you.', 'D.H. Lawrence', 'English writer and poet', 'Life'),
('Life is inherently risky. There is only one big risk you should avoid at all costs, and that is the risk of doing nothing.', 'Denis Waitley', 'American motivational speaker and author', 'Life'),
('The more you praise and celebrate your life, the more there is in life to celebrate.', 'Oprah Winfrey', 'American talk show host, television producer, and philanthropist', 'Life'),
('Go confidently in the direction of your dreams. Live the life you have imagined.', 'Henry David Thoreau', 'American naturalist, essayist, and philosopher', 'Life'),
('Life consists not in holding good cards but in playing those you hold well.', 'Josh Billings', 'American humorist and lecturer', 'Life'),
('Life is like a camera. Focus on whats important, capture the good times, develop from the negatives, and if things do not work out, take another shot.', 'Unknown', 'Anonymous', 'Life'),
('Only a life lived for others is a life worthwhile.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Life'),
('Life is short, break the rules, forgive quickly, kiss slowly, love truly, laugh uncontrollably, and never regret anything that made you smile.', 'Mark Twain', 'American writer and humorist', 'Life'),
('Never let the fear of striking out keep you from playing the game.', 'Babe Ruth', 'American professional baseball player', 'Life'),
('Life is not measured by the number of breaths we take, but by the moments that take our breath away.', 'Maya Angelou', 'American memoirist, poet, and civil rights activist', 'Life'),
('The biggest adventure you can take is to live the life of your dreams.', 'Oprah Winfrey', 'American talk show host, television producer, and philanthropist', 'Life'),
('Life is a great big canvas, and you should throw all the paint on it you can.', 'Danny Kaye', 'American actor and comedian', 'Life');

-- Change (50)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('Be the change that you wish to see in the world.', 'Mahatma Gandhi', 'Indian lawyer and anti-colonial nationalist', 'Change'),
('The only way to make sense out of change is to plunge into it, move with it, and join the dance.', 'Alan Watts', 'British philosopher and writer', 'Change'),
('Change is the law of life. And those who look only to the past or present are certain to miss the future.', 'John F. Kennedy', '35th President of the United States', 'Change'),
('Progress is impossible without change, and those who cannot change their minds cannot change anything.', 'George Bernard Shaw', 'Irish playwright, critic, and political activist', 'Change'),
('The secret of change is to focus all of your energy not on fighting the old, but on building the new.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Change'),
('Change your thoughts and you change your world.', 'Norman Vincent Peale', 'American minister and author', 'Change'),
('If you do not like something, change it. If you cannot change it, change your attitude.', 'Maya Angelou', 'American memoirist, poet, and civil rights activist', 'Change'),
('Everyone thinks of changing the world, but no one thinks of changing himself.', 'Leo Tolstoy', 'Russian writer', 'Change'),
('Change is hard at first, messy in the middle and gorgeous at the end.', 'Robin Sharma', 'Canadian writer and motivational speaker', 'Change'),
('Things do not change; we change.', 'Henry David Thoreau', 'American naturalist, essayist, and philosopher', 'Change'),
('The measure of intelligence is the ability to change.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Change'),
('To improve is to change; to be perfect is to change often.', 'Winston Churchill', 'British Prime Minister during World War II', 'Change'),
('Change before you have to.', 'Jack Welch', 'American business executive', 'Change'),
('Life belongs to the living, and he who lives must be prepared for changes.', 'Johann Wolfgang von Goethe', 'German writer and statesman', 'Change'),
('You cannot change what you are, only what you do.', 'Philip Pullman', 'English author', 'Change'),
('True life is lived when tiny changes occur.', 'Leo Tolstoy', 'Russian writer', 'Change'),
('If you want to change the world, start with yourself.', 'Mahatma Gandhi', 'Indian lawyer and anti-colonial nationalist', 'Change'),
('Change is inevitable. Growth is optional.', 'John C. Maxwell', 'American author and speaker', 'Change'),
('All great changes are preceded by chaos.', 'Deepak Chopra', 'Indian-American author and alternative medicine advocate', 'Change'),
('Only the wisest and stupidest of men never change.', 'Confucius', 'Chinese philosopher and politician', 'Change'),
('Nothing is so painful to the human mind as a great and sudden change.', 'Mary Shelley', 'English novelist', 'Change'),
('The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Change'),
('Change will not come if we wait for some other person or some other time.', 'Barack Obama', '44th President of the United States', 'Change'),
('You are always free to change your mind and choose a different future, or a different past.', 'Richard Bach', 'American writer', 'Change'),
('Any change, even a change for the better, is always accompanied by drawbacks and discomforts.', 'Arnold Bennett', 'English writer', 'Change'),
('It is not the strongest of the species that survives, nor the most intelligent. It is the one most adaptable to change.', 'Charles Darwin', 'English naturalist', 'Change'),
('Incredible change happens in your life when you decide to take control of what you do have power over instead of craving control over what you do not.', 'Steve Maraboli', 'American author and speaker', 'Change'),
('Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', 'Rumi', 'Persian poet, Islamic scholar, and Sufi mystic', 'Change'),
('When we are no longer able to change a situation, we are challenged to change ourselves.', 'Viktor Frankl', 'Austrian neurologist, psychiatrist, and Holocaust survivor', 'Change'),
('They always say time changes things, but you actually have to change them yourself.', 'Andy Warhol', 'American artist and filmmaker', 'Change'),
('Change is painful, but nothing is as painful as staying stuck somewhere you do not belong.', 'Mandy Hale', 'American author', 'Change'),
('We cannot become what we want by remaining what we are.', 'Max DePree', 'American businessman and writer', 'Change'),
('Education is the most powerful weapon which you can use to change the world.', 'Nelson Mandela', 'South African anti-apartheid revolutionary and political leader', 'Change'),
('I alone cannot change the world, but I can cast a stone across the waters to create many ripples.', 'Mother Teresa', 'Albanian-Indian Catholic nun and missionary', 'Change'),
('The art of life lies in a constant readjustment to our surroundings.', 'Kakuzo Okakura', 'Japanese scholar', 'Change'),
('If you change the way you look at things, the things you look at change.', 'Wayne Dyer', 'American author and motivational speaker', 'Change'),
('One child, one teacher, one book, one pen can change the world.', 'Malala Yousafzai', 'Pakistani activist for female education', 'Change'),
('Without change there is no innovation, creativity, or incentive for improvement.', 'William Pollard', 'American physicist', 'Change'),
('For changes to be of any true value, they have to be lasting and consistent.', 'Tony Robbins', 'American author, coach, and motivational speaker', 'Change'),
('Taking a new step, uttering a new word, is what people fear most.', 'Fyodor Dostoevsky', 'Russian novelist', 'Change'),
('Change in all things is sweet.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Change'),
('The first step toward change is awareness. The second step is acceptance.', 'Nathaniel Branden', 'Canadian-American psychotherapist', 'Change'),
('You must be the change you wish to see in the world.', 'Mahatma Gandhi', 'Indian lawyer and anti-colonial nationalist', 'Change'),
('Change is the end result of all true learning.', 'Leo Buscaglia', 'American author and motivational speaker', 'Change'),
('Those who cannot change their minds cannot change anything.', 'George Bernard Shaw', 'Irish playwright, critic, and political activist', 'Change'),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Change'),
('Faced with the choice between changing ones mind and proving that there is no need to do so, almost everyone gets busy on the proof.', 'John Kenneth Galbraith', 'Canadian-American economist', 'Change'),
('Every moment is a fresh beginning.', 'T.S. Eliot', 'British-American poet and essayist', 'Change'),
('In any given moment we have two options: to step forward into growth or step back into safety.', 'Abraham Maslow', 'American psychologist', 'Change'),
('God grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference.', 'Reinhold Niebuhr', 'American theologian', 'Change');

-- Friendship (50)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('A friend is someone who knows all about you and still loves you.', 'Elbert Hubbard', 'American writer and philosopher', 'Friendship'),
('Walking with a friend in the dark is better than walking alone in the light.', 'Helen Keller', 'American author and disability rights advocate', 'Friendship'),
('A real friend is one who walks in when the rest of the world walks out.', 'Walter Winchell', 'American newspaper and radio gossip commentator', 'Friendship'),
('Friendship is born at that moment when one person says to another, What! You too? I thought I was the only one.', 'C.S. Lewis', 'British writer and theologian', 'Friendship'),
('The only way to have a friend is to be one.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Friendship'),
('Friends are the siblings God never gave us.', 'Mencius', 'Chinese Confucian philosopher', 'Friendship'),
('True friendship comes when the silence between two people is comfortable.', 'David Tyson', 'Author', 'Friendship'),
('There is nothing on this earth more to be prized than true friendship.', 'Thomas Aquinas', 'Italian Dominican friar, philosopher, and theologian', 'Friendship'),
('A friend is one of the nicest things you can have, and one of the best things you can be.', 'Douglas Pagels', 'American author', 'Friendship'),
('The language of friendship is not words but meanings.', 'Henry David Thoreau', 'American naturalist, essayist, and philosopher', 'Friendship'),
('A single rose can be my garden... a single friend, my world.', 'Leo Buscaglia', 'American author and motivational speaker', 'Friendship'),
('The greatest gift of life is friendship, and I have received it.', 'Hubert H. Humphrey', 'American politician', 'Friendship'),
('Friendship is the only cement that will ever hold the world together.', 'Woodrow Wilson', '28th President of the United States', 'Friendship'),
('What is a friend? A single soul dwelling in two bodies.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Friendship'),
('Friends show their love in times of trouble, not in happiness.', 'Euripides', 'Ancient Greek tragedian', 'Friendship'),
('Be slow to fall into friendship, but when you are in, continue firm and constant.', 'Socrates', 'Classical Greek philosopher, founder of Western philosophy', 'Friendship'),
('A true friend never gets in your way unless you happen to be going down.', 'Arnold H. Glasow', 'American businessman and humorist', 'Friendship'),
('A friend to all is a friend to none.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Friendship'),
('In the sweetness of friendship let there be laughter, and sharing of pleasures.', 'Khalil Gibran', 'Lebanese-American writer and poet', 'Friendship'),
('One loyal friend is worth ten thousand relatives.', 'Euripides', 'Ancient Greek tragedian', 'Friendship'),
('Wishing to be friends is quick work, but friendship is a slow ripening fruit.', 'Aristotle', 'Ancient Greek philosopher and scientist', 'Friendship'),
('Lots of people want to ride with you in the limo, but what you want is someone who will take the bus with you when the limo breaks down.', 'Oprah Winfrey', 'American talk show host, television producer, and philanthropist', 'Friendship'),
('The best mirror is an old friend.', 'George Herbert', 'Welsh-born poet and orator', 'Friendship'),
('Friendship is like a glass ornament, once it is broken it can rarely be put back together exactly the same way.', 'Charles Kingsley', 'English clergyman and novelist', 'Friendship'),
('I would rather walk with a friend in the dark, than alone in the light.', 'Helen Keller', 'American author and disability rights advocate', 'Friendship'),
('My best friend is the one who brings out the best in me.', 'Henry Ford', 'American industrialist and founder of Ford Motor Company', 'Friendship'),
('A friend is what the heart needs all the time.', 'Henry Van Dyke', 'American author and clergyman', 'Friendship'),
('Friendship is one mind in two bodies.', 'Mencius', 'Chinese Confucian philosopher', 'Friendship'),
('No person is your friend who demands your silence, or denies your right to grow.', 'Alice Walker', 'American novelist and poet', 'Friendship'),
('A sweet friendship refreshes the soul.', 'Proverbs 27:9', 'Biblical wisdom', 'Friendship'),
('Good friends are like stars. You do not always see them, but you know they are always there.', 'Unknown', 'Anonymous', 'Friendship'),
('There are no strangers here; only friends you have not yet met.', 'William Butler Yeats', 'Irish poet', 'Friendship'),
('Count your age by friends, not years. Count your life by smiles, not tears.', 'John Lennon', 'English singer, songwriter, and peace activist', 'Friendship'),
('It is not a lack of love, but a lack of friendship that makes unhappy marriages.', 'Friedrich Nietzsche', 'German philosopher, cultural critic, and poet', 'Friendship'),
('The real test of friendship is can you literally do nothing with the other person? Can you enjoy those moments of life that are utterly simple?', 'Eugene Kennedy', 'American priest and author', 'Friendship'),
('The most beautiful discovery true friends make is that they can grow separately without growing apart.', 'Elisabeth Foley', 'Author', 'Friendship'),
('Tis the privilege of friendship to talk nonsense, and to have her nonsense respected.', 'Charles Lamb', 'English essayist', 'Friendship'),
('Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.', 'Marcel Proust', 'French novelist', 'Friendship'),
('Many people will walk in and out of your life, but only true friends will leave footprints in your heart.', 'Eleanor Roosevelt', 'American political figure and First Lady', 'Friendship'),
('Friendship improves happiness and abates misery, by the doubling of our joy and the dividing of our grief.', 'Marcus Tullius Cicero', 'Roman statesman, orator, and philosopher', 'Friendship'),
('The ornament of a house is the friends who frequent it.', 'Ralph Waldo Emerson', 'American essayist, lecturer, philosopher, and poet', 'Friendship'),
('Do not be afraid of new friends.', 'Alice Walker', 'American novelist and poet', 'Friendship'),
('How many slams in an old screen door? Depends how loud you shut it. How many slices in a bread? Depends how thin you cut it.', 'Shel Silverstein', 'American writer and cartoonist', 'Friendship'),
('Friends are those rare people who ask how we are and then wait to hear the answer.', 'Ed Cunningham', 'American football player', 'Friendship'),
('A friend may be waiting behind a strangers face.', 'Maya Angelou', 'American memoirist, poet, and civil rights activist', 'Friendship'),
('Some people go to priests; others to poetry; I to my friends.', 'Virginia Woolf', 'English writer', 'Friendship'),
('Rare as is true love, true friendship is rarer.', 'Jean de La Fontaine', 'French fabulist and poet', 'Friendship'),
('Friendship is always a sweet responsibility, never an opportunity.', 'Khalil Gibran', 'Lebanese-American writer and poet', 'Friendship'),
('Each friend represents a world in us, a world possibly not born until they arrive.', 'Anaïs Nin', 'French-Cuban-American diarist and essayist', 'Friendship'),
('One of the most beautiful qualities of true friendship is to understand and to be understood.', 'Lucius Annaeus Seneca', 'Roman Stoic philosopher, statesman, and dramatist', 'Friendship');

-- Time (50)
INSERT INTO quotes (text, author, author_bio, genre) VALUES
('Time is what we want most, but what we use worst.', 'William Penn', 'English writer and founder of Pennsylvania', 'Time'),
('Lost time is never found again.', 'Benjamin Franklin', 'Founding Father of the United States', 'Time'),
('The two most powerful warriors are patience and time.', 'Leo Tolstoy', 'Russian writer', 'Time'),
('Time flies over us, but leaves its shadow behind.', 'Nathaniel Hawthorne', 'American novelist and short story writer', 'Time'),
('Better three hours too soon than a minute too late.', 'William Shakespeare', 'English playwright, poet, and actor', 'Time'),
('Time is the wisest counselor of all.', 'Pericles', 'Greek statesman and orator', 'Time'),
('They always say time changes things, but you actually have to change them yourself.', 'Andy Warhol', 'American artist and filmmaker', 'Time'),
('Time is the most valuable thing a man can spend.', 'Theophrastus', 'Greek philosopher', 'Time'),
('Time is a created thing. To say I do not have time is like saying I do not want to.', 'Lao Tzu', 'Ancient Chinese philosopher and writer', 'Time'),
('The bad news is time flies. The good news is you are the pilot.', 'Michael Altshuler', 'American entrepreneur', 'Time'),
('Time and tide wait for no man.', 'Geoffrey Chaucer', 'English poet and author', 'Time'),
('The key is in not spending time, but in investing it.', 'Stephen R. Covey', 'American educator, author, and businessman', 'Time'),
('Time is free, but it is priceless. You cannot own it, but you can use it.', 'Harvey Mackay', 'American businessman and author', 'Time'),
('Time is a great healer, but a poor beautician.', 'Lucille S. Harper', 'Author', 'Time'),
('Your time is limited, do not waste it living someone elses life.', 'Steve Jobs', 'Co-founder of Apple Inc.', 'Time'),
('Time is the longest distance between two places.', 'Tennessee Williams', 'American playwright', 'Time'),
('The common man is not concerned about the passage of time, the man of talent is driven by it.', 'Arthur Schopenhauer', 'German philosopher', 'Time'),
('Time you enjoy wasting is not wasted time.', 'Marthe Troly-Curtin', 'British author', 'Time'),
('How we spend our days is, of course, how we spend our lives.', 'Annie Dillard', 'American author', 'Time'),
('Time is the coin of your life. It is the only coin you have, and only you can determine how it will be spent.', 'Carl Sandburg', 'American poet', 'Time'),
('A man who dares to waste one hour of time has not discovered the value of life.', 'Charles Darwin', 'English naturalist', 'Time'),
('Time is an illusion.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Time'),
('The past is behind, learn from it. The future is ahead, prepare for it. The present is here, live it.', 'Thomas S. Monson', 'American religious leader', 'Time'),
('Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.', 'Mother Teresa', 'Albanian-Indian Catholic nun and missionary', 'Time'),
('Time waits for no one.', 'Unknown', 'Anonymous', 'Time'),
('Time brings all things to pass.', 'Aeschylus', 'Ancient Greek tragedian', 'Time'),
('Time is a dressmaker specializing in alterations.', 'Faith Baldwin', 'American author', 'Time'),
('One thing you cannot recycle is wasted time.', 'Unknown', 'Anonymous', 'Time'),
('The only reason for time is so that everything does not happen at once.', 'Albert Einstein', 'Theoretical physicist who developed the theory of relativity', 'Time'),
('Time is the school in which we learn, time is the fire in which we burn.', 'Delmore Schwartz', 'American poet', 'Time'),
('Punctuality is the thief of time.', 'Oscar Wilde', 'Irish poet and playwright', 'Time'),
('Time has a way of showing us what really matters.', 'Margaret Peters', 'Author', 'Time'),
('We must use time wisely and forever realize that the time is always ripe to do right.', 'Nelson Mandela', 'South African anti-apartheid revolutionary and political leader', 'Time'),
('Time changes everything except something within us which is always surprised by change.', 'Thomas Hardy', 'English novelist and poet', 'Time'),
('Time spent laughing is time spent with the gods.', 'Japanese Proverb', 'Traditional Japanese wisdom', 'Time'),
('Until you value yourself, you will not value your time.', 'M. Scott Peck', 'American psychiatrist and author', 'Time'),
('You will never find time for anything. If you want time, you must make it.', 'Charles Buxton', 'English brewer and philanthropist', 'Time'),
('Dost thou love life? Then do not squander time, for that is the stuff life is made of.', 'Benjamin Franklin', 'Founding Father of the United States', 'Time'),
('Time is really the only capital that any human being has, and the only thing he cannot afford to lose.', 'Thomas Edison', 'American inventor and businessman', 'Time'),
('There is never enough time to do everything, but there is always enough time to do the most important thing.', 'Brian Tracy', 'Canadian-American motivational speaker and author', 'Time'),
('Time is a game played beautifully by children.', 'Heraclitus', 'Pre-Socratic Greek philosopher', 'Time'),
('Regret for wasted time is more wasted time.', 'Mason Cooley', 'American aphorist', 'Time'),
('Time discovers truth.', 'Seneca', 'Roman Stoic philosopher, statesman, and dramatist', 'Time'),
('Time makes heroes but dissolves celebrities.', 'Daniel J. Boorstin', 'American historian and author', 'Time'),
('Time is what prevents everything from happening at once.', 'John Archibald Wheeler', 'American theoretical physicist', 'Time'),
('Time is the reef upon which all our frail mystic ships are wrecked.', 'Noel Coward', 'English playwright and composer', 'Time'),
('Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.', 'Zig Ziglar', 'American author and motivational speaker', 'Time'),
('We are not given a short life but we make it short, and we are not ill-supplied but wasteful of it.', 'Seneca', 'Roman Stoic philosopher, statesman, and dramatist', 'Time'),
('Time cools, time clarifies; no mood can be maintained quite unaltered through the course of hours.', 'Thomas Mann', 'German novelist', 'Time'),
('Time, which changes people, does not alter the image we have retained of them.', 'Marcel Proust', 'French novelist', 'Time');
